name: Deploy to FTP

on:
  push:
    branches:
      - master

concurrency:
  group: cv-production-ftp
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      # Install project dependencies
      - name: Install project dependencies
        run: npm ci

      # Install lftp
      - name: Install lftp
        run: sudo apt-get install -y lftp

      # Build Angular
      - name: Build Angular
        run: npm run build -- --configuration production

      # Deploy to FTP
      - name: Deploy to FTP
        run: |
          lftp -e "set ftp:ssl-allow no; set mirror:use-pget-n 5; mirror --reverse --delete --verbose=3 --no-perms --exclude .well-known/ --exclude web.config ./dist/curriculum-vitae /${{ secrets.FTP_DIR }}; bye" ftp://${{ secrets.FTP_HOST }} -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASS }}
